const sidebars = {
  news: [ // ← 关键修改：ID 必须与 plugin 的 id 一致
    'index',
    {
      type: 'category',
      label: '2025年9月',
      items: [
        { type: 'autogenerated', dirName: '202509' }
      ],
    },
  ],
};
export default sidebars;