// sidebars.js
const sidebars = {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      label: '简介',
      customProps: {
        sidebar_icon: 'BookOpen',
      },
    },
    {
      type: 'doc',
      id: 'Docusaurus-Integration-Giscus-Review',
      label: 'Docusaurus 集成 Giscus 评论',
      customProps: {
        sidebar_icon: 'MessageCircle',
      },
    },
    {
      type: 'doc',
      id: 'WeChat-Mini-Program-Review-Process',
      label: '微信小程序审核流程',
      customProps: {
        sidebar_icon: 'CheckCircle',
      },
    },
    {
      type: 'doc',
      id: 'video-ceshi',
      label: '视频测试',
      customProps: {
        sidebar_icon: 'Video',
      },
    },
    {
      type: 'category',
      label: 'Cloudflare Usage',
      customProps: {
        sidebar_icon: 'Cloud',
      },
      items: [
        { type: 'autogenerated', dirName: 'cloudflare' }
      ],
    },
    {
      type: 'category',
      label: 'Automated Script Code Set',
      customProps: {
        sidebar_icon: 'Code',
      },
      items: [
        { type: 'autogenerated', dirName: 'script' }
      ],
    },
    {
      type: 'category',
      label: '教程命令大全',
      customProps: {
        sidebar_icon: 'Terminal',
      },
      items: [
        { type: 'autogenerated', dirName: 'Command-List' }
      ],
    },
    {
      type: 'category',
      label: '若善云系统教程',
      customProps: {
        sidebar_icon: 'Server',
      },
      items: [
        { type: 'autogenerated', dirName: 'tutorial-system' }
      ],
    },
    {
      type: 'category',
      label: '企业微信教程',
      customProps: {
        sidebar_icon: 'Briefcase',
      },
      items: [
        { type: 'autogenerated', dirName: 'tutorial-extras' }
      ],
    },
  ],
};

export default sidebars;