const sidebars = {
  os: [ // ← 关键修改：ID 必须与 plugin 的 id 一致
    'index',
    {
      type: 'category',
      label: '第一期',
      items: [
        { type: 'autogenerated', dirName: 'no1' }
      ],
    },
    {
      type: 'category',
      label: '第二期',
      items: [
        { type: 'autogenerated', dirName: 'no2' }
      ],
    },
  ],
};
export default sidebars;