const sidebars = {
  docs: [
    
        'intro',
        'video-ceshi',
    {
      type: 'category',
      label: 'Cloudflare Usage',
      items: [
        { type: 'autogenerated', dirName: 'cloudflare' }
      ],
    },
    {
      type: 'category',
      label: '若善云系统教程',
      items: [
        { type: 'autogenerated', dirName: 'tutorial-system' }
      ],
    },
    {
      type: 'category',
      label: '企业微信教程',
      items: [
        { type: 'autogenerated', dirName: 'tutorial-extras' }
      ],
    },
  ],

};

export default sidebars;