// sidebars.js
const sidebars = {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      label: '简介',
      customProps: {
        sidebar_icon: 'BookOpen',
      },
    },
    {
      type: 'doc',
      id: 'RDP-Wrapper-Multi-User-Management-System',
      label: 'RDP Wrapper 多用户管理系统',
      customProps: {
        sidebar_icon: 'Layers',
      },
    },
    {
      type: 'doc',
      id: 'HTTPS-certificate',
      label: '多服务器环境下的自动化 HTTPS 证书全生命周期管理',
      customProps: {
        sidebar_icon: 'Lock',
      },
    },
    {
      type: 'doc',
      id: 'nobel-prizes',
      label: '诺贝尔奖数据集可视化分析',
      customProps: {
        sidebar_icon: 'Award',
      },
    },
    {
      type: 'doc',
      id: 'Docusaurus-Integration-Giscus-Review',
      label: 'Docusaurus 集成 Giscus 评论',
      customProps: {
        sidebar_icon: 'MessageCircle',
      },
    },
    {
      type: 'doc',
      id: 'All-AILLM-models',
      label: '世界范围内所有的 AI / LLM 模型、提供商与主流应用',
      customProps: {
        sidebar_icon: 'Brain',
      },
    },
    {
      type: 'doc',
      id: 'WeChat-Mini-Program-Review-Process',
      label: '微信小程序审核流程',
      customProps: {
        sidebar_icon: 'CheckCircle',
      },
    },
    {
      type: 'doc',
      id: 'Cloudflare-VPN',
      label: '基于 Cloudflare Workers 与 Pages 边缘计算服务搭建私人VPN代理节点',
      customProps: {
        sidebar_icon: 'Shield',
      },
    },
    {
      type: 'doc',
      id: 'GitHub-Actions',
      label: '企业级 GitHub Actions CI/CD 操作手册',
      customProps: {
        sidebar_icon: 'GitBranch',
      },
    },
    {
      type: 'doc',
      id: 'video-ceshi',
      label: '视频测试',
      customProps: {
        sidebar_icon: 'Video',
      },
    },
{
  type: 'category',
  label: '健康生活行动',
  customProps: {
    sidebar_icon: 'Cloud', // ✅ Feather 中存在
  },
  items: [
    { type: 'autogenerated', dirName: 'Health-Action' }
  ],
},
{
  type: 'category',
  label: 'Cloudflare Usage',
  customProps: {
    sidebar_icon: 'Cloud', // ✅ Feather 中存在
  },
  items: [
    { type: 'autogenerated', dirName: 'cloudflare' }
  ],
},
{
  type: 'category',
  label: 'Automated Script Code Set',
  customProps: {
    sidebar_icon: 'FileCode', // ✅ 替代 'Code'，Feather 中存在
    // 或者用 'Code' 的近似：'FileCode' 不存在，所以用 'FileText'
  },
  items: [
    { type: 'autogenerated', dirName: 'script' }
  ],
},
{
  type: 'category',
  label: '教程命令大全',
  customProps: {
    sidebar_icon: 'Terminal', // ✅ 替代 'Terminal'，Feather 中存在
  },
  items: [
    { type: 'autogenerated', dirName: 'Command-List' }
  ],
},
{
  type: 'category',
  label: '若善云系统教程',
  customProps: {
    sidebar_icon: 'Server', // ✅ 替代 'Server'，Feather 中存在
  },
  items: [
    { type: 'autogenerated', dirName: 'tutorial-system' }
  ],
},
{
  type: 'category',
  label: '企业微信教程',
  customProps: {
    sidebar_icon: 'Briefcase', // ✅ 存在，正确！
  },
  items: [
    { type: 'autogenerated', dirName: 'tutorial-extras' }
  ],
}
  ],
};

export default sidebars;